### ISSUE TITLE
orientations and creation of these files

### ISSUE THREAD

**Issue by krober10nd** [gempy-project/gempy#225]
Hello, 

Is it possible to provide/enhance a simple tutorial that explains what the orientation parameters can do (range of reasonable values, physical meaning with a simple diagram)? It's fairly unclear coming from a different geophysical background (other than geology) and attempting to develop geological models with this software package what dip, plane, and polarity actually mean and example 1 starts with these data as a given. Also, how did you create these csv files in the examples, for instance? Maybe it would be useful to a wider audience to explain that. 

Thank you for your time!

**Comment by Leguark** [comment]
Orientations constrain the stratigraphic direction. They can be anywhere in space and basically they force a scalar field to be perpendicular at that point. You can see more details in the gempy paper about that.

Gradient can be given as directional components (Gx, Gy, Gz) or dip, azimuth, polarity--which is perpendicular to it.

The input data of gempy are mainly coordinates and categories (which point belong to each surface and which surface belong to which series). The csv files you can create by hand or you can use pandas directly on pandas or any other pythonic way to pass the data in gempy.

I agree that tutorials can always be improved. More specific feedback and help to keep them up to date is always welcome!

**Comment by fastamo** [comment]
Documentation on how orientation works in GemPy was recently added with #279

**Comment by fastamo** [comment]
A tutorial that better explains orientations should still be made.

**Comment by pkoutla** [comment]
Hi there, and thanks for the code and all the effort! There are still some dark areas on how the file of orientations is created. 

Below there are my questions-thoughts: 

In the orientation file:
1) According to your example (i am running the 'ch1-1_Basics.ipynb'), why there are only 3 rows? --> I would expect 5 (at least one per formation type) 
2) How did you find the XYZ?  --> it seems to make no sense to me. Do they refer to the centroids of a plane? 
3) Following the question above, there are 3 orientations; one for the fault, one from the left side of the fault and the other from the right side of the fault. Do we need to select the XYZ in a such deviation in order to capture their orientation (from G_x, G_y, G_z) in comparison with the fault? Will this make the fault normal or reverse?  (please see the image attached and the arrows:
![Fault](https://user-images.githubusercontent.com/43598924/80364470-ad277800-888e-11ea-99ce-61ce1b1dff69.png)
)
4) Is 'Azimuth' measured by the dip direction or the strike? 

Thank you very much for your time and i am looking forward for your answer!

**Comment by hadismasihi** [comment]
I agree with the opinions of friends, and in this regard, it is necessary to provide training so that people understand how to select and determine the direction of these geological aircraft. These codes will not be very useful for us until we have the correct basic information.

**Comment by AlexanderJuestel** [comment]
@hadismasihi and @pkoutla,

maybe I can clarify some of the issues :)

1. I assume you are looking at the example below. In Gempy, each series needs to have at least one orientation. So the fault gets one orientation. Then a "Strat_Series" was defined containing multiple surfaces. Putting multiple surfaces into one series indicates that these layers are assumed to be parallel to subparallel and can be modelled with just one scalar field, hence, you would only need one orientation for one of the layers. Here it was decided to add one orientation to the Shale surface and one to the second Sandstone. Actually mentioning already what you pointed out in bullet 3, you will need at least one orientation per fault block so that GemPy can construct the potential field on both sides of the fault. 

![image](https://user-images.githubusercontent.com/45469915/127765326-e179e806-09b4-4001-8209-7e872b337ca3.png)

![image](https://user-images.githubusercontent.com/45469915/127765316-1bb3c1cb-dc1e-479b-ac91-285be6d17316.png)

2. The XYZ coordinates for orientations are rather flexible based on my experience. However, they should be somewhat close to the location of a proposed fault surface or layer boundary. The XY location is especially important for layer boundaries. 

3. Also going back to bullet 1 you will need at least one orientation per fault block. Otherwise, GemPy may throw an error and cannot calculate the potential field. The style of the fault (normal, reverse) will be determined by the position of the layers in both hanging and footwall. The orientations have no influence on that. 

4. The azimuth is the plunging direction of a fault. The plunging direction may not always be the strike direction of a fault mapped at the surface but it may be a good first guess. If you see that a different azimuth may work better with the modelled results, feel free to adjust the azimuth. 


I hope I could help you both a little. We are planning on creating some tutorial videos and to ramp up development again but our main developers are currently pursuing other opportunities.

**Comment by lj-cug** [comment]
Both of GemPy and LoopStructural are wonderful implicit geological modelling tools, Thanks for your contributions. But I also get confused about the input data file (CSV) including so much information about the stratigraphy and fault. How can I generate them? Use what software? Usually fault's XYZ coordinates are easily interpreted from seismic data.
