### ISSUE TITLE
Import borehole data

### ISSUE THREAD

**Issue by flohorovicic** [gempy-project/gempy#282]
Import borehole data from the conventional formats

**Comment by pytzcarraldo** [comment]
I think that's a great idea and long overdue!

But what are these "conventional" formats? I think scope will be really important here. 

It might be worth looking what's already covered by `lasio` , `welly` and `striplog` 
https://github.com/kinverarity1/lasio
https://github.com/agile-geoscience/welly
https://github.com/agile-geoscience/striplog

Otherwise this could also be part of / fused into `subsurface` and help the project get off the ground
https://github.com/softwareunderground/subsurface

As subsurface file I/O is a messy jungle of utter confusion of galactic proportions 😄, I'd think putting that directly as part of GemPy would just lend itself to becoming a non-standardized mess 🤔

**Comment by Leguark** [comment]
yes, this has to go to subsurface, together with the reader you wrote for peterel and a I/O @lachlangrose wrote for gocad.

@pytzcarraldo can you ask Matt to create a dev team and maybe given us some writing rights?

**Comment by pytzcarraldo** [comment]
@Leguark  I have writing rights to the repository, so pull requests could always go via me. otherwise I can of course ask Matt to add you or others

**Comment by Leguark** [comment]
that is good to know we can start via pull request but I guess we should do a subsurface dev team soonish. Maybe you have rights for that?

**Comment by Michael-P-Crisp** [comment]
Hi,

Has there been any further consideration given to this? I have a feeling that libraries like welly and striplog are no longer being actively developed, since the organisation that working on them (Agile) has closed down: https://agilescientific.com/blog/2022/7/14/agile-is-closing

One versatile data format often used for ground investigation data is AGS 4 https://www.ags.org.uk/data-format/ags4-data-format/
There's at least one library available for reading AGS data: https://pypi.org/project/python-ags4/

In theory, attributes from say the GEOL table could be made into a striplog object, and the merge_neighbours method could be called, since there could easily be adjacent intervals with the same formation/stratum name.

**Comment by Japhiolite** [comment]
Hi Michael,

We certainly have to be on the lookout, you're right. 
I'm not sure about the future of welly, striplog, bruges etc., but I'm optimistic, that they will stay despite Agile* closing.
Currently, all this is used in [subsurface](https://github.com/softwareunderground/subsurface) which can be used for parsing borehole data. 

Cheers

**Comment by Didymograptus** [comment]
I'm involved with the AGS and the AGS4 library. I'm keen to see if we can automate getting data from AGS into Gempy. Please let me know if I can be of any help.

Note that we also have an interpreted model  transfer format AGSi https://www.ags.org.uk/data-format/agsi-ground-model/
This is new and we're looking for integration with modelling software, I've reviewing Gempy to understand its io capability for AGSi.

Cheers
Tony

**Comment by AlexanderJuestel** [comment]
@Didymograptus, what we could also think about is implementing such an import function into our GemGIS (https://github.com/cgre-aachen/gemgis) package. It was created to get data faster into and out of GemPy. Maybe that would be a good place for it, also to keep the API of GemPy clean :)

**Comment by Didymograptus** [comment]
Yes, agree 100% to keep GemPy as clean as possible. I'll take a look at GemGIS and pick this up on the issues over there.

**Comment by Leguark** [comment]
After gempy v3 release, next will be subsurface. Hopefully we can create the data gateway that we always intended there

**Comment by AlexanderJuestel** [comment]
@Leguark, just FYI: I am currently working on my own borehole data package (https://github.com/AlexanderJuestel/pyborehole) using lasio and dlisio. Maybe this is something to look at as well :)
