### ISSUE TITLE
Export to vtk is still under the old api

### ISSUE THREAD

**Issue by Leguark** [gempy-project/gempy#445]
copying and paste export to vtk function

**Comment by shakasaki** [comment]
I still could not figure out how to export a surface from a gempy model to a vtk graphics object, so that I can open it with paraview for example. I though this relates to this post. 
I essentially create a surface in a model using points and their orientations, and would like to export this sufrace to vtk formal. I'm using gempy 2.2.3

Apologies if I'm repeating something and thanks for the help

**Comment by AndrewAnnex** [comment]
@Leguark I think I have a pr that addresses this partially by using pyvista instead. I have found it easier to make all my grid objects in pyvista and use the compute_model(at= call that reduces all of that code to a dozen or so lines.
