### ISSUE TITLE
3D visualizations make Google Colab kernel crash

### ISSUE THREAD

**Issue by JoostGevaert** [gempy-project/gempy#901]
I put the 1.1 - Basics of geological modeling with GemPy Jupyter Notebook in my Google Drive and then opened it with Google Colab.

Installation of GemPy and PyVista was successful. Unfortunately, 3D visualizations seem to make the Google Colab kernel crash:
```python
gpv.plot_3d(geo_model, image=False, plotter_type='basic')
```
```python
gpv.plot_3d(geo_model, show_data=False, image=False, plotter_type='basic')
```

**To Reproduce**
Run this Google Colab:
https://drive.google.com/file/d/1gnIs9azy8wYQHuYatSziNYaea2lr5_x9/view

**Comment by javoha** [comment]
Hi,
so I think the problem here is that the default 3D gempy plot/pyvista wants to open an interactive plot in a new window. To my knowledge this does not currently work with Google Colab. Other plotting options ("notebook" for example) have not yet been implemented in gempy_v3 (but will hopefully be available in the close future).
For now this piece of code worked for me to get a static 3D plot in Colab:

```
import pyvista

pyvista.set_jupyter_backend('static')
pyvista.global_theme.notebook = True
pyvista.start_xvfb()

gpv.plot_3d(data, image=True)
```

**Comment by JoostGevaert** [comment]
Great. Thanks Jan!
